#!/bin/sh
# $Id: clock,v 1.1 2005/08/29 01:21:07 softcraft Exp $
###
##
# /etc/init.d/clock - Set the system clock.
#
# 2004-09-11 Generations Linux <info@softcraft.org>
##
###

. /etc/init.d/functions

ARC=0
SRM=0
UTC=0

if [ -f /etc/sysconfig/clock ]; then
   . /etc/sysconfig/clock

   # convert old style clock config to new values
   if [ "${CLOCKMODE}" = "GMT" ]; then
      UTC=true
   elif [ "${CLOCKMODE}" = "ARC" ]; then
      ARC=true
   fi
fi

CLOCKDEF=""
CLOCKFLAGS="$CLOCKFLAGS --hctosys"

case "$ARC" in
     yes|true)
     	CLOCKFLAGS="$CLOCKFLAGS --arc";
     	CLOCKDEF="$CLOCKDEF (arc)";
     ;;
esac
case "$SRM" in
     yes|true)
	CLOCKFLAGS="$CLOCKFLAGS --srm";
	CLOCKDEF="$CLOCKDEF (srm)";
     ;;
esac
case "$UTC" in
   yes|true)
    CLOCKFLAGS="$CLOCKFLAGS --utc";
    CLOCKDEF="$CLOCKDEF (utc)";
   ;;
   no|false)
    CLOCKFLAGS="$CLOCKFLAGS --localtime";
    CLOCKDEF="$CLOCKDEF (localtime)";
   ;;
esac

/sbin/hwclock $CLOCKFLAGS
action $"Setting clock $CLOCKDEF: `date`" date

# </clock>
