#! /bin/sh
# $Id: ircd,v 1.1 2005/08/29 01:21:07 softcraft Exp $
###
##
# /etc/init.d/ircd - start/stop IRC server
#
# 2004-07-07 Generations Linux <info@softcraft.org>
##
###

# Source function library.
. /etc/init.d/functions

# Source configuration files
. /etc/sysconfig/network
[ -r /etc/ircd.conf ] || exit 0

# See how we were called.
case "$1" in
  start)
	echo -n "Starting IRC system: "
	su irc -c /usr/sbin/ircd
	touch /var/lock/subsys/ircd
	;;
  stop)
	echo -n "Stopping IRC service: "
	killproc ircd
	rm -f /var/lock/subsys/ircd
	;;
  status)
	status ircd
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit 0
