#!/bin/sh
# $Id: isdnutils,v 1.1 2005/08/29 01:21:07 softcraft Exp $
###
##
# /etc/init.d/isdnutils start/stop/restart/status ISDN utilities
#
# 2004-11-08 Generations Linux <info@softcraft.org>
##
###
test -f /usr/sbin/isdnctrl || exit 0    # sanity check
. /etc/init.d/functions

NAME=isdnutils
PATH=/bin:/usr/bin:/sbin:/usr/sbin
FLAGS="defaults"

# isdn_verbose=true     # default is set by VERBOSE in /etc/default/rcS
[ -r /etc/sysconfig/isdn ] && . /etc/sysconfig/isdn

case "$1" in
  start)
    echo -n "Starting isdn services..."
    start_devices
    start_ipppd
    start_iprofd
    if [ -s /usr/sbin/isdnlog ]; then start_isdnlog; fi
    ;;
  stop)
    echo -n "Stopping isdn services..."
    stop_iprofd
    stop_ipppd
    stop_devices
    if [ -s /usr/sbin/isdnlog ]; then stop_isdnlog; fi
    ;;
  restart|force-reload)
    # reload doesn't really work for these daemons...
    echo -n "Restarting isdn services :"
    isdn_verbose=false
    stop_iprofd
    stop_ipppd
    if [ -s /usr/sbin/isdnlog ]; then stop_isdnlog; start_isdnlog; fi
    stop_devices; start_devices
    start_ipppd
    start_iprofd
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

echo "."
list_unconfigured

exit 0
# vim:set ts=8:
