#!/bin/sh
#
# Linux /etc/init.d script to start/stop the mdnsd daemon.
# Copyright (c) 2002-2003 Apple Computer, Inc. All rights reserved.
#
# @APPLE_LICENSE_HEADER_START@
# 
# This file contains Original Code and/or Modifications of Original Code
# as defined in and that are subject to the Apple Public Source License
# Version 2.0 (the 'License'). You may not use this file except in
# compliance with the License. Please obtain a copy of the License at
# http://www.opensource.apple.com/apsl/ and read it before using this
# file.
# 
# The Original Code and all software distributed under the License are
# distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
# EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
# INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
# Please see the License for the specific language governing rights and
# limitations under the License.
# 
# @APPLE_LICENSE_HEADER_END@
#
# $Log: mdns,v $
# Revision 1.1  2005/08/29 01:21:07  softcraft
# initial checkin
#
# Revision 1.6  2004/12/07 20:30:45  cheshire
# Fix start-stop-daemon for Suse Linux (don't use -s TERM)
#
# Revision 1.5  2004/06/29 22:13:45  cheshire
# Fix from Andrew White at NICTA
#
# Revision 1.4  2004/02/05 20:23:10  cheshire
# Fix mdnsd.sh to work on *BSD distributions
#
# Revision 1.3  2004/01/19 22:47:17  cheshire
# Define killprocterm() to do "killproc $1 -TERM" for Linux
#
# Revision 1.2  2003/12/11 19:42:13  cheshire
# Change name "mDNSResponderd" to "mdnsd" for consistency with standard Linux (Unix) naming conventions
#
# Revision 1.1  2003/12/08 20:47:02  rpantos
# Add support for mDNSResponder on Linux.
#
# The following lines are used by the *BSD rcorder system to decide
# the order it's going to run the rc.d scripts at startup time.
# PROVIDE: mdnsd
# REQUIRE: NETWORKING
#

##
# 2005-04-10 Generations Linux <info@softcraft.org>
#
PROGRAM=mdnsd
[ -x `type -p $PROGRAM` ] || exit 0

#SERVICE="Apple Darwin Multicast DNS / DNS Service Discovery daemon"
SERVICE="DNS Service Discovery daemon"

# System wide library functions
. /etc/init.d/functions

# $SERVICE specific resources
PIDFILE=/var/run/$PROGRAM.pid

# See how we were called.
case "$1" in
    start)
	if [ ! -f $PIDFILE ]; then
	  echo -n "Starting $SERVICE... $PROGRAM"
	  daemon $PROGRAM
          echo
	else
	  $0 status
	fi
	;;

    stop)
	if [ -f $PIDFILE ]; then
          echo -n "Stopping $SERVICE... $PROGRAM"
          killproc $PROGRAM
          echo
	else
	  $0 status
	fi
	;;

    restart)
	$0 stop
        $0 start
	;;

    status)
	status mdnsd
	;;
    *)
	echo "Usage: /etc/init.d/mdns {start|stop|restart|status}"
	exit 1
	;;
esac

exit 0
