#!/bin/sh
# $Id: modules,v 1.3 2005/09/13 15:38:48 softcraft Exp $
###
##
# modules - This file is executed by init scripts to explicitly
#           load kernel modules before finishing up system boot.
#
# 2005-01-09 Generations Linux <info@softcraft.org>
##
###

# Source function library.
. /etc/init.d/functions

# Configure Plug and Play boards.
if ! grep -iq nopnp /proc/cmdline >/dev/null 2>&1 ; then
  [ -x /sbin/isapnp -a -f /etc/isapnp.conf -a ! -f /proc/isapnp ] && \
  action $"Setting up ISA PNP devices: " /sbin/isapnp /etc/isapnp.conf
fi

# Source system boot configuration parameters
[ -f /etc/sysconfig/boot ] && . /etc/sysconfig/boot

# Start hotpluggable subsystems (coldplugging.)
[ -x /etc/init.d/hotplug ] && /etc/init.d/hotplug start

# udev - configurable dynamic device naming support initialization
[ -z "$INSTALLED" -a -x /sbin/udevstart ] && udevstart
sleep 4;chmod 666 /dev/dsp /dev/mixer /dev/null /dev/random /dev/tty /dev/zero

# Advanced Configuration and Power Interface
if [ -n "$ACPI" ]; then
  echo -n "Loading ACPI modules..."

  for MODULE in $ACPI; do
    modprobe $MODULE >/dev/null 2>&1
    echo -n " $MODULE"
  done

  echo_success
  echo
fi

# Activate SCSI emulation when specified.
if grep -q "ide-scsi" /proc/cmdline ; then
  action $"Loading SCSI emulation: " modprobe ide-scsi 2> /dev/null
fi

# Activate sound system.
[ -f /etc/sysconfig/sound ] && . /etc/sysconfig/sound

if [ -n "$DRIVER" -a "$DRIVER" != "unknown" ]; then
  action $"Loading sound driver $DRIVER: " modprobe $DRIVER 2> /dev/null
  [ -n "$INIT" ] && $INIT 2> /dev/null
fi

# Additional modules...
[ -f /etc/sysconfig/modules ] && \
for name in `grep -v ^# /etc/sysconfig/modules`; do
  action $"Loading module $name: " modprobe $name 2> /dev/null
done

# </modules>
